/* auto-generated by fsm_gen.py */

#include "fsm_driver.hpp"
#include "Events.hpp"
#include "fsm_fifo.hpp"
#include "tinyfsm.hpp"
#include "FSM1.hpp"

using my_fsm = tinyfsm::FsmList<FSM1>;

TIMER_1_EVENT TIMER_1_EVENT_SINGLETON = TIMER_1_EVENT();

void start_fsm_driver() {
    FSM_Event event;

    my_fsm::start();

    while (1) {
        if (read_event(&event)) {
            switch (event) {
            case TIMER_1_EVENT_INDEX: my_fsm::dispatch(TIMER_1_EVENT_SINGLETON);break;
            }
        }
    }
}

