/* auto-generated by fsm_gen.py */

#include "fsm_driver.hpp"
#include "Events.hpp"
#include "fsm_fifo.hpp"
#include "tinyfsm.hpp"
#include "FSM1.hpp"
#include "FSM2.hpp"

using my_fsm = tinyfsm::FsmList<FSM1, FSM2>;

SWAP_EVENT SWAP_EVENT_SINGLETON = SWAP_EVENT();
REPEAT_EVENT REPEAT_EVENT_SINGLETON = REPEAT_EVENT();

void start_fsm_driver() {
    FSM_Event event;

    my_fsm::start();

    while (1) {
        if (read_event(&event)) {
            switch (event) {
            case SWAP_EVENT_INDEX: my_fsm::dispatch(SWAP_EVENT_SINGLETON);break;
            case REPEAT_EVENT_INDEX: my_fsm::dispatch(REPEAT_EVENT_SINGLETON);break;
            }
        }
    }
}

