/* auto-generated by fsm_gen.py */

#ifndef EVENTS_HPP_
#define EVENTS_HPP_

#include "tinyfsm.hpp"

typedef enum {
    TIMER_3 = 0,
    TIMER_1 = 1,
    TIMER_2 = 2,
    NUM_TIMERS = 3
} Timer;

/* TODO: Implement these functions in a user file! */
void start_timer(Timer timer, int ms);
void stop_timer(Timer timer);

struct BASE_EVENT : tinyfsm::Event {};

struct TIMER_3_EVENT : BASE_EVENT {};
struct TIMER_1_EVENT : BASE_EVENT {};
struct TIMER_2_EVENT : BASE_EVENT {};

#endif /* EVENTS_HPP_ */

