/* auto-generated by fsm_gen.py */

#ifndef FSM_FIFO_HPP_
#define FSM_FIFO_HPP_

#include "Events.hpp"

#define FIFO_SIZE 100

typedef enum {
    TIMER_3_EVENT_INDEX,
    TIMER_1_EVENT_INDEX,
    TIMER_2_EVENT_INDEX
} FSM_Event;

typedef struct {
    int head = 0;
    int tail = 0;
    FSM_Event buffer[FIFO_SIZE];
} Event_FIFO;

void write_event(FSM_Event event);
int read_event(FSM_Event *event);

#endif /* FSM_FIFO_HPP_ */

