/* auto-generated by fsm_gen.py */

#include "FSM1.hpp"

class FSM1_S01;    /* (ENTRY)One */
class FSM1_S02;    /* Two */
class FSM1_S03;    /* Three */

class FSM1_S01 : public FSM1 {
    void entry() {
        state_S01();
    }

    void react(NEXT_EVENT const &) override {
        transit<FSM1_S02>();
    }
};

class FSM1_S02 : public FSM1 {
    void entry() {
        state_S02();
        transit<FSM1_S03>();
    }

    void react(UNCONDITIONAL const &) override {
        transit<FSM1_S03>();
    }
};

class FSM1_S03 : public FSM1 {
    void entry() {
        state_S03();
    }

    void react(NEXT_EVENT const &) override {
        transit<FSM1_S01>();
    }
};

FSM_INITIAL_STATE(FSM1, FSM1_S01);

