/* auto-generated by fsm_gen.py */

#include "fsm_driver.hpp"
#include "Events.hpp"
#include "fsm_fifo.hpp"
#include "tinyfsm.hpp"
#include "FSM1.hpp"

using my_fsm = tinyfsm::FsmList<FSM1>;

UNCONDITIONAL UNCONDITIONAL_SINGLETON = UNCONDITIONAL();
NEXT_EVENT NEXT_EVENT_SINGLETON = NEXT_EVENT();

void start_fsm_driver() {
    FSM_Event event;

    my_fsm::start();

    while (1) {
        if (read_event(&event)) {
            switch (event) {
            case UNCONDITIONAL_INDEX: my_fsm::dispatch(UNCONDITIONAL_SINGLETON);break;
            case NEXT_EVENT_INDEX: my_fsm::dispatch(NEXT_EVENT_SINGLETON);break;
            }
        }
    }
}

