/* auto-generated by fsm_gen.py */

#ifndef EVENTS_HPP_
#define EVENTS_HPP_

#include "tinyfsm.hpp"

typedef enum {
    NUM_TIMERS = 0
} Timer;

/* TODO: Implement these functions in a user file! */
void start_timer(Timer timer, int ms);
void stop_timer(Timer timer);

struct BASE_EVENT : tinyfsm::Event {};

struct SWAP_EVENT : BASE_EVENT {};
struct REPEAT_EVENT : BASE_EVENT {};

#endif /* EVENTS_HPP_ */

