/* auto-generated by fsm_gen.py */

#ifndef FSM2_HPP_
#define FSM2_HPP_

#include "Events.hpp"
#include "tinyfsm.hpp"
#include "user_states.hpp"

class FSM2 : public tinyfsm::Fsm<FSM2> {
public:
    void react(tinyfsm::Event const &) {};
    virtual void entry(void) {};
    virtual void exit(void) {};

    virtual void react(SWAP_EVENT const &) {};
    virtual void react(REPEAT_EVENT const &) {};
};

#endif /* FSM2_HPP_ */

