/* auto-generated by fsm_gen.py */

#include "FSM1.hpp"

class FSM1_S00;    /* (ENTRY)One */
class FSM1_S01;    /* Two */

class FSM1_S00 : public FSM1 {
    void entry() {
        state_S00();
    }

    void react(REPEAT_EVENT const &) override {
        transit<FSM1_S00>();
    }

    void react(SWAP_EVENT const &) override {
        transit<FSM1_S01>();
    }
};

class FSM1_S01 : public FSM1 {
    void entry() {
        state_S01();
    }

    void react(SWAP_EVENT const &) override {
        transit<FSM1_S00>();
    }

    void react(REPEAT_EVENT const &) override {
        transit<FSM1_S01>();
    }
};

FSM_INITIAL_STATE(FSM1, FSM1_S00);

