/* auto-generated by fsm_gen.py */

#include "FSM2.hpp"

class FSM2_S03;    /* (ENTRY)Three */
class FSM2_S04;    /* Four */

class FSM2_S03 : public FSM2 {
    void entry() {
        state_S03();
    }

    void react(REPEAT_EVENT const &) override {
        transit<FSM2_S03>();
    }

    void react(SWAP_EVENT const &) override {
        transit<FSM2_S04>();
    }
};

class FSM2_S04 : public FSM2 {
    void entry() {
        state_S04();
    }

    void react(SWAP_EVENT const &) override {
        transit<FSM2_S03>();
    }

    void react(REPEAT_EVENT const &) override {
        transit<FSM2_S04>();
    }
};

FSM_INITIAL_STATE(FSM2, FSM2_S03);

