/* auto-generated by fsm_gen.py */

#ifndef FSM1_HPP_
#define FSM1_HPP_

#include "Events.hpp"
#include "tinyfsm.hpp"
#include "user_states.hpp"

class FSM1 : public tinyfsm::Fsm<FSM1> {
public:
    void react(tinyfsm::Event const &) {};
    virtual void entry(void) {};
    virtual void exit(void) {};

    virtual void react(TIMER_1_EVENT const &) {};
};

#endif /* FSM1_HPP_ */

