/* auto-generated by fsm_gen.py */

#ifndef FSM3_HPP_
#define FSM3_HPP_

#include "Events.hpp"
#include "tinyfsm.hpp"
#include "user_states.hpp"

class FSM3 : public tinyfsm::Fsm<FSM3> {
public:
    void react(tinyfsm::Event const &) {};
    virtual void entry(void) {};
    virtual void exit(void) {};

    virtual void react(TIMER_3_EVENT const &) {};
};

#endif /* FSM3_HPP_ */

