/* auto-generated by fsm_gen.py */

#include "FSM1.hpp"

class FSM1_S02;    /* Two */
class FSM1_S01;    /* (ENTRY)One */

class FSM1_S02 : public FSM1 {
    void entry() {
        start_timer(TIMER_1, 1000);
        state_S02();
    }

    void react(TIMER_1_EVENT const &) override {
        stop_timer(TIMER_1);
        transit<FSM1_S01>();
    }
};

class FSM1_S01 : public FSM1 {
    void entry() {
        start_timer(TIMER_1, 1000);
        state_S01();
    }

    void react(TIMER_1_EVENT const &) override {
        stop_timer(TIMER_1);
        transit<FSM1_S02>();
    }
};

FSM_INITIAL_STATE(FSM1, FSM1_S01);

