/* auto-generated by fsm_gen.py */

#include "FSM3.hpp"

class FSM3_S05;    /* (ENTRY)Five */
class FSM3_S06;    /* Six */

class FSM3_S05 : public FSM3 {
    void entry() {
        start_timer(TIMER_3, 250);
        state_S05();
    }

    void react(TIMER_3_EVENT const &) override {
        stop_timer(TIMER_3);
        transit<FSM3_S06>();
    }
};

class FSM3_S06 : public FSM3 {
    void entry() {
        start_timer(TIMER_3, 250);
        state_S06();
    }

    void react(TIMER_3_EVENT const &) override {
        stop_timer(TIMER_3);
        transit<FSM3_S05>();
    }
};

FSM_INITIAL_STATE(FSM3, FSM3_S05);

