/* auto-generated by fsm_gen.py */

#include "fsm_driver.hpp"
#include "Events.hpp"
#include "fsm_fifo.hpp"
#include "tinyfsm.hpp"
#include "FSM1.hpp"

using my_fsm = tinyfsm::FsmList<FSM1>;

REPEAT_EVENT REPEAT_EVENT_SINGLETON = REPEAT_EVENT();
SWAP2_EVENT SWAP2_EVENT_SINGLETON = SWAP2_EVENT();
SWAP1_EVENT SWAP1_EVENT_SINGLETON = SWAP1_EVENT();

void start_fsm_driver() {
    FSM_Event event;

    my_fsm::start();

    while (1) {
        if (read_event(&event)) {
            switch (event) {
            case REPEAT_EVENT_INDEX: my_fsm::dispatch(REPEAT_EVENT_SINGLETON);break;
            case SWAP2_EVENT_INDEX: my_fsm::dispatch(SWAP2_EVENT_SINGLETON);break;
            case SWAP1_EVENT_INDEX: my_fsm::dispatch(SWAP1_EVENT_SINGLETON);break;
            }
        }
    }
}

